### ISSUE TITLE
Sometime can't speak  on Quest V17.

### ISSUE THREAD

**Issue by huangjun198604** [AgoraIO/Agora-Unity-Quickstart#1]
有时候打开别的程序没退出再进入sdk时候能听到别人声音，但是自己说不出声音，
怀疑初始化时候音频设备被占用或者相关问题，
平台是oculus quest v17版本
unity 2018.4LTS

**Comment by zhangtao1104** [comment]
是的，某些平台 录音设备在某一个 时刻，只能被一处占用，那就会存在设备抢占的问题。
这个是系统限制。

可以通过比较好的逻辑来控制这个问题，比如在 OnApplicationPause 中 去调用 DisableAudio/EnableAudio 。确保自己当前的程序在 退到后台后，释放录音设备。

**Comment by huangjun198604** [comment]
主要是没办法控制前面程序的关闭，因为oculus quest是接近单任务系统，能否打开程序时候让系统强行释放了之前占用的录音设备然后每次都正常打开？

**Comment by zhangtao1104** [comment]
这样是不行的，强制不了，录音设备在 Android 端大多数 rom 都是单焦点。如果前一个程序抢占了 不释放，后面的程序想去抢占都是用不了的。除非是系统的内置程序，有系统的最高权限 是可以做到的。

如果你想要用实时语音，又想用 oculus 的录音，那这种场景是不行的。不能同时抢占的。

这种情况有两种解决办法，就启用一处的录音，然后取出 pcm 放到另一个程序中。

**Comment by huangjun198604** [comment]
ok,我设置了延时几秒启动应该是解决了
