### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by NeoHoffa** [AgoraIO/Agora-Unity-Quickstart#11]
The link on the Quickstart-VideoChat page under "Integration and run" is broken.

https://github.com/AgoraIO/Agora-Unity-Quickstart/tree/master/QuickStart-VideoChat#integration-and-run

Results in a 502 Bad Gateway

**Comment by plutoless** [comment]
@NeoHoffa thanks for reporting. i just did a test and it's working fine. Could you maybe try again again? might be temp server issues at that time.
![image](https://user-images.githubusercontent.com/471561/103163387-536db800-4838-11eb-8b69-c41c25929f1e.png)
