### ISSUE TITLE
App Screen Sharing has cropped width

### ISSUE THREAD

**Issue by ROBYER1** [AgoraIO/Agora-Unity-Quickstart#13]
App screen sharing is cropped on the width, it seems some aspect ratios are not supported
This cropping is visible clearly in the documentation even in the example screenshots, so if it is expected behaviour, it means that some areas of the screen are cropped which is inadequate for our use cases which require a proper full-screen view.

https://docs.agora.io/en/Video/screensharing_unity?platform=Unity

Screen shot from docs:
![image](https://user-images.githubusercontent.com/10745594/108184705-68ade700-7103-11eb-86f8-d19c60e85ce2.png)

This affects:
1. Advanced Demos App Screen Sharing Sample: https://github.com/AgoraIO/Agora-Unity-Quickstart/tree/master/Advanced-Demos
2. Screen Sharing Sample: https://github.com/AgoraIO/Agora-Unity-Quickstart/tree/master/API-Example-Unity/Assets/API-Example/screenshare-sample

Using:

-Agora SDK Asset Store Version 3.2.1.72 - February 01, 2021
-Unity 2020.2.4f1
-Windows 10/Mac Big Su
-IOS 14/Android 10

Very simple to replicate:
1. Use the **screen sharing example** or the **advanced demos App screen share example**
2. Build from Unity to an ipad or phone
3. Share app screen between the editor and the phone to see the shared screen from the phone is cropped in width

We have been unable to find a fix and **the cropping doesn't seem to happen when sharing between Unity Editors**, however there is a hint below from another user on the Agora Slack channel that may help:

From **Stamblew** on Agora Slack:
"the problem was the video dimensions set at the VideoEncoderConfiguration instance. Some dimensions are not accepted by Agora, so it falls back to a default one, I guess, which crops the video frame."

**Comment by icywind** [comment]
[copying my comment from Slack]
There are two issues here.  First the Web demo has a canvas to show contents with cropping.  So it is not a perfect example to examine the issue.    Secondly, it is true that the encoder only takes certain resolution ratio.  You can verify this by register the OnVideoSizeChanged callback.  When the ipad (mine is 1536x2048) starts to run, you can see the callback returns the changed size to 720x1280.  Which is the ratio of cropped image you see in Editor.

**Comment by plutoless** [comment]
@ROBYER1 and to add the reason why web is cropping the content is because it's using "cover" mode for content hint option. if you use "contain" it will display all content.

**Comment by ROBYER1** [comment]
> @ROBYER1 and to add the reason why web is cropping the content is because it's using "cover" mode for content hint option. if you use "contain" it will display all content (but you will see black edges)

This doesn't apply to me I am using Unity Editor and a built app on IOS/Android, I can see the raw exact video feed coming in and it is cropped as @icywind mentioned.

What you mention with the image fitting is a different problem that can be easily fixed.

**Comment by icywind** [comment]
Rob, I've updated the Adv. Demo+ with fall back dimension to avoid cropping.
