### ISSUE TITLE
Example for the Signaling API? 

### ISSUE THREAD

**Issue by ROBYER1** [AgoraIO/Agora-Unity-Quickstart#14]
I couldn't see any documentation reference for using the signaling API in the Unity SDK here https://docs.agora.io/en/Voice/API%20Reference/unity/index.html

It would be very useful to have a simple example of the signaling API in the quickstart examples - for example sending a message or transmitting the transform.position of an object as a Vector3 over the signal

**Comment by yoreland** [comment]
You might be interested in this:
https://github.com/AgoraIO-Community/Agora-Unity-RTM-SDK
