### ISSUE TITLE
Sdk hard to learn.

### ISSUE THREAD

**Issue by huangjun198604** [AgoraIO/Agora-Unity-Quickstart#2]
Unity sdk模板学习比较困难，
建议考虑用户习惯，弄一些通用行的，
别人项目拉进去可以用。
我是改了老一阵子才用上。
你写成一些简单通用的模块（类似photon的），
别人搞得项目就会快很多。

**Comment by zhangtao1104** [comment]
目前集成的话，有两种方式：
1: 通过 Unity Asset Store， 直接 Download package, Import package 到你的项目中，直接就可以去调用 API。

2: 通过 Agora 官网，Download package, 把 Demo 中 Plugin 直接拖入你的 Project，把 AgoraGamingSDK 中的 Scripts 中拖入你的 Project 中，就可以直接调用 api 了。

上面两种方式我们集成指南上都有详细介绍：
https://docs.agora.io/cn/Video/start_call_unity?platform=Unity

我不清楚你说的学习比较困难是指哪部分？可以帮忙说下吗？

**Comment by huangjun198604** [comment]
例如将一些重要参数（例如fps之类）public或者Zerializable比较方便入门填写。和写好的C#或者prefab能直接用（例如登入，显示的prefab），前期搭建的效率起码是看api的几十倍~

**Comment by zhangtao1104** [comment]
其实你说的是两种不同的方式。
使用 public 或者 Sericalizable 让用户来设置变量的很常见。
使用 api 来设置的也是比较常见的。
谢谢你的建议，我们会去考虑评估你的建议。

**Comment by huangjun198604** [comment]
提个建议unity得sdk可以按中间件的想法去规划可能会更好用

**Comment by icywind** [comment]
@huangjun198604 你的建议不错。 有没有时间，把你觉得前期搭建很必须的东西列个表？我们可以更好的跟进。
