### ISSUE TITLE
permissions not granted for Mac screenshare

### ISSUE THREAD

**Issue by AfifSoussi** [AgoraIO/Agora-Unity-Quickstart#24]
Hello, thanks for this Demo it got me up and running, the only thing i couldn't get to work is screensharing on Mac OS.
it only show the game view, i need to requests permissions for screen recording, 
but i couldn't find the command to do it . can you help me please ? 
thanks !

**Comment by zhangtao1104** [comment]
If you want to ask for screen record permission, you need to call the apple sdk api named CGWindowListCreateImage or CGDisplayCreateImage to request permission, It will pop a permission request dialog when you call the api for the first time and then you need to go to the System&perference to open or close the permission.

you can reset the permission by this command: tccutil reset ScreenCapture
