### ISSUE TITLE
Can't sign APP with signcode.sh

### ISSUE THREAD

**Issue by artemsivcev** [AgoraIO/Agora-Unity-Quickstart#27]
I'm folowing this instruction to sign my Unity project.
<img width="692" alt="Screenshot 2021-07-28 at 14 00 50" src="https://user-images.githubusercontent.com/5911567/127318754-98492280-08bc-4e2e-a810-17700d10a339.png">
But after last step I have many errors that files not fount
<img width="1108" alt="Screenshot 2021-07-28 at 14 02 03" src="https://user-images.githubusercontent.com/5911567/127318902-2e12d65e-edd8-4ebc-a8db-10ad7a43065e.png">
If i try to sign manualy, i have an error: **AgoraRtcKit.framework: code object is not signed at all**
Can't find how to fix this. Plz help

**Comment by zhangtao1104** [comment]
Do you download the sdk from unity asset store or agora offical website?

**Comment by zhangtao1104** [comment]
May be you can try to download the sdk from offical website.
https://download.agora.io/sdk/release/Agora_Unity_RTC_SDK_3.4.6_video_20210723_117.zip

**Comment by artemsivcev** [comment]
I found solution. Need to choose right certificate for right things. If your want to notarize app  use Developer ID Application certificate. For more information use this [instruction](https://gist.github.com/dpid/270bdb6c1011fe07211edf431b2d0fe4) and yes, you need to sign every lib and file in agoraSdkCWrapper
