### ISSUE TITLE
Windows Crash when Share Screen

### ISSUE THREAD

**Issue by artemsivcev** [AgoraIO/Agora-Unity-Quickstart#29]
Im successfully implement ShareScreen for MacOS and Windows, but when I try to run ShareScreen on Windows 10 Home Edition I have a crash... There is only feedback from user, don't have all information yet

**Comment by zhangtao1104** [comment]
Do you implement ScreenShare according to this demo: https://github.com/AgoraIO/Agora-Unity-Quickstart/blob/master/API-Example-Unity/Assets/API-Example/desktop-screen-share-sample/DesktopScreenShare.cs ?

**Comment by artemsivcev** [comment]
Yes, there was a problem with some versions of windows. Screen's id's does not starts with 0 some times.
