### ISSUE TITLE
SDK iOS build script

### ISSUE THREAD

**Issue by sebastianewak** [AgoraIO/Agora-Unity-Quickstart#33]
It's more of an SDK feature request, but I didn't find a better place to post it. Hopefully, it's ok.

In the `BL_BuildPostProcess` there is a line with an assumed base path:

`const string defaultLocationInProj = "AgoraEngine/Plugins/iOS";`

I think, the assumption here is that `AgoraEngine` is placed directly in the `Assets` folder, which is not always the case, at least for the commercial projects, that I've worked on.

Usually, any dependencies are stored in a subfolder like `Assets/3rdParty/` or `Assets/ThirdParty/`.

It would be nice if the script would actually read the base path allowing more flexibility (if possible, I don't have much experience with writing editor scripts).

It's definitely not critical, but I'm sure it would save at least a few people from debugging their iOS build errors, so it might be worth considering :)

**Comment by zhangtao1104** [comment]
Thanks for your suggestion.

**Comment by zhangtao1104** [comment]
We will try to improve the expercience of our sdk.

**Comment by sebastianewak** [comment]
Thank you! :)
