### ISSUE TITLE
How to share screen from Unity (Android/iOS) to Web

### ISSUE THREAD

**Issue by pitrees** [AgoraIO/Agora-Unity-Quickstart#4]
Hi Agora,

I've a working unity app with web client ready.
However when I try to share screen from Unity, the video bytes that send to Agora is not looking good at web client.

This is due to ReadPixels in Unity can only be done with Texture in RGB / RGBA format.
Agora external video pixel format only support BGRA.

What's the workaround for this issue?

**Comment by zhangtao1104** [comment]
We have RGBA32 support in the latest unity sdk.  You can give me an email address, i can send it to you. @pitrees

**Comment by pitrees** [comment]
> We have RGBA32 support in the latest unity sdk. You can give me an email address, i can send it to you. @pitrees

Sure, pls send to 1pitrees@gmail.com

Just to let you know, Im using ReadPixels in RGBA32, but Agora only support BGRA, so the receiver end video color looks weird with what I have currently.

**Comment by zhangtao1104** [comment]
Out newest unity sdk 3.0.1 was published already, you can try to use the it. It support RGBA32 now.
