### ISSUE TITLE
Share Screen on M1

### ISSUE THREAD

**Issue by artemsivcev** [AgoraIO/Agora-Unity-Quickstart#40]
On Mac's with M1 Share Screen show's this error:
`DllNotFoundException: ShareScreenLib assembly:<unknown assembly> type:<unknown type> member:(null)
AgoraNativeBridge.GetMacDisplayIds () (at <3762ab1ebfe84eabbefe6a203560b1d8>:0)
DesktopScreenShare.ShareDisplayScreen () (at <3762ab1ebfe84eabbefe6a203560b1d8>:0)
ShareScreenController.Share () (at <3762ab1ebfe84eabbefe6a203560b1d8>:0)
ShareScreenController.Update () (at <3762ab1ebfe84eabbefe6a203560b1d8>:0)`

**Comment by HugoChaan** [comment]
Hello, there is a readme in the ScreenShareOnDesktop demo, which has a download link, you could download ShareScreenLib from there.

**Comment by artemsivcev** [comment]
Yeah, I know, but it does not work with M1. You need to recompile ShareScreenLib with new version of XCode with adding Cocoa.framework. Otherwise there was an error on compilation with NSScreen for arm64
<img width="1396" alt="Screenshot 2021-11-04 at 10 05 39" src="https://user-images.githubusercontent.com/5911567/140286738-9e65f430-d5c1-40b2-957e-67b2e551b3ad.png">
.

**Comment by icywind** [comment]
note: the online copy of the bundle has been update according to your notes.  Thank you for your input!
