### ISSUE TITLE
The type or namespace name 'agora_gaming_rtc' could not be found

### ISSUE THREAD

**Issue by CKJBlueStar** [AgoraIO/Agora-Unity-Quickstart#45]
I want to playing demo but a lot of not found error is glad to me.
how can I solve it?

**Comment by icywind** [comment]
Please make sure you download and import the [Agora Video SDK.](https://assetstore.unity.com/packages/tools/video/agora-video-sdk-for-unity-134502)

**Comment by CKJBlueStar** [comment]
> Please make sure you download and import the [Agora Video SDK.](https://assetstore.unity.com/packages/tools/video/agora-video-sdk-for-unity-134502)

thx
