### ISSUE TITLE
Can I use this SDK to encode the Unity camera video to rtmp stream end send it to a server?

### ISSUE THREAD

**Issue by gengwb** [AgoraIO/Agora-Unity-Quickstart#46]
Can I use this SDK to encode the Unity camera video to rtmp stream end send it to a server?

**Comment by icywind** [comment]
Yes, see the Transcoding example in [Advanced Demo app](https://github.com/AgoraIO/Agora-Unity-Quickstart/tree/master/Advanced-Demos)
