### ISSUE TITLE
Agora on laptop in advanced demo uses webcam with no option to turn off or not use webcam

### ISSUE THREAD

**Issue by pnguyen2232** [AgoraIO/Agora-Unity-Quickstart#47]
I start the project in Unity 2019.4.0f1. I press "Desktop Screen Share" after putting in an agora stream channel.

I am greeted with my webcam turned on. I click "Share display" once and it will switch to the desktop screen. 

![image](https://user-images.githubusercontent.com/16747212/151905244-81f99c14-1f7f-4d3e-ad22-d30c953649b0.png)

There is no way to prevent webcam turning on, or an option to ignore it. I've attempted to debug the code for AgoraNativeBridge.MONITORINFO but these return either 40 or single digit values in Unity so I can't exactly tell what is monitor and what is a webcam.

**Comment by HugoChaan** [comment]
Hello, We no longer maintain the code in the advanced demo. If you want to try the screen sharing function, please use the example in the link: [ScreenShareOnDesktop](https://github.com/AgoraIO/Agora-Unity-Quickstart/tree/master/API-Example-Unity/Assets/API-Example/examples/advanced/ScreenShareOnDesktop)

**Comment by icywind** [comment]
@pnguyen2232 - the webcam is turned off when you are sharing the display.  Before that, the demo shows the local video from webcam as default.  To completely turn off the webcam, you can call EnableLocalVideo(false) when setting up the Agora engine.
