### ISSUE TITLE
Video feed rotated 180°

### ISSUE THREAD

**Issue by mamuelsraz** [AgoraIO/Agora-Unity-Quickstart#49]
The video feed received from the SDK (android and Windows PC) is always rotated 180 degrees. The example project "fixes" this by rotating the plane on which the feed is projected.
I suppose this is just a hack, is there a proper way to receive not rotated  feed?

**Comment by icywind** [comment]
That's a know behavior of how Unity captures image. You will just have to flip your transform accordingly.  The demo code gives example how to do that.
