### ISSUE TITLE
Screen Share

### ISSUE THREAD

**Issue by etkinss** [AgoraIO/Agora-Unity-Quickstart#6]
I've tried to implement rtc.PushVideoFrame alternatives(StartScreenCaptureByScreenRect, StartScreenCaptureByWindowId) but couldn't manage to share screen. I am only getting an white box. Do you have an example for full screen sharing?

**Comment by icywind** [comment]
Please refer to the advanced demos in this repo: https://bit.ly/2RRP5tK

**Comment by shomz** [comment]
This is still relevant. No matter what I do, I still get the white screen on the client app.
